Controllers/CreateCarController.cs
using CarShop.Data.Interfaces;
using CarShop.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarShop.Controllers
{
    public class CreateCarController: Controller
    {
        private readonly ICreateCar _allOrders;
        

        public CreateCarController(ICreateCar allOrders)
        {
            _allOrders = allOrders;
            
        }
        public IActionResult Checkout() //Шаблон, но над которым потом будут происходить какие-то действия
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Car order)
        {
           
            if (ModelState.IsValid)//Если все данные верно заполнены
            {
                _allOrders.CreateCars(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }
        public IActionResult Complete()
        {
            ViewBag.Message = "Звказ успешно оформлен";
            return View();
        }

    }
}

Controllers/ShopCartController.cs
using CarShop.Data.Interfaces;
using CarShop.Data.Models;
using CarShop.Pages;
using Microsoft.AspNetCore.Mvc;
using CarShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarShop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRep;
        private readonly ShopCarts _shopCarts;

        public ShopCartController(IAllCars carRep, ShopCarts shopCarts)
        {
            _carRep = carRep;
            _shopCarts = shopCarts;
        }

        public ViewResult Index() //отображает опред. Html шаблон и отображает корзину 
        {
            var items = _shopCarts.GetShopItems();
            _shopCarts.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCarts = _shopCarts
            };

            return View(obj);
        }

        public RedirectToActionResult AddToCart(int ID) //Добавляет тавары в корзину и переадресовывает на другую страничку
        {
            var _item = _carRep.Cars.FirstOrDefault(i => i.ID == ID);//выбирает нужный товар из BD списка всех товаров
            if (_item != null) // выбрали ли мы объект
            {
                _shopCarts.AddTOCart(_item);
            }
            return RedirectToAction("Index");
        }
    }
    
}

Pages/Shared/Allcars.cshtml
@model CarShop.Data.Models.Car


<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model._img" alt="@Model._name" />
    <h2>@Model._name</h2>

    <p> @Model._shortDesc </p>
    <p> Цена: @Model._price.ToString("c")</p>
    
    <p> <a class="btn btn-warning" asp-controller="ShopCart" asp-action="AddToCart" asp-route-ID="@Model.ID">Оформить покупку</a> </p>
</div>
    

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CarShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ShopCart" asp-action="Index">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="CreateCar" asp-action="Checkout">Добавить объявление</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Политика конфиденциальности</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CarShop - <a asp-area="" asp-page="/Privacy">Политика кофиденциальности</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>